version: '3.8'

services:
  mongo:
    image: mongo
    container_name: agenticaiapp_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: agenticaiapp_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://smk:root@cluster0.gtbu9.mongodb.net/agenticaiapp
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: agenticaiapp_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8000

volumes:
  mongo_data:
